In [99]:
# 01. Load the diabetes dataset into a Pandas dataframe

import pandas as pd

df = pd.read_csv("diabetes.csv")

In [100]:
# 02. Display the first 5 records

df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [101]:
# 03. Display first ten records of the dataset

df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [102]:
# 04. Display the last five records of the dataset.

df.tail(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [103]:
# 05. Display last ten records of the dataset

df.tail(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [104]:
# 06. Display the number of rows and columns in the dataset.

df.shape

(768, 9)

In [105]:
# 07. Display all column names.

df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [106]:
# 08. Display the data types of all columns

df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [107]:
# 09. Display complete information about dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [108]:
# 10. Display the number of unique values of each columns

df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [109]:
# 11. Display the unique values in the outcome columns

df["Outcome"].unique()

array([1, 0], dtype=int64)

In [110]:
# 12. Count the number of patients in each outcome category

df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [111]:
# 13. Idetify the target variable

target_variable = "Outcome"

print("Target Variable: ", target_variable)

Target Variable:  Outcome

In [112]:
# 14. Seperate the features and target variable

X = df.drop("Outcome", axis=1)
Y = df["Outcome"]

print("Features: ", X)

print("\nTarget Variable: ", Y)

Features:       Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

Target Variable:  0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [113]:
# 15. Generate a statistical summary of the dataset

df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [114]:
# 16. Find the average value of each numerical column

df.mean(numeric_only=True)

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [115]:
# 17. Find the median value of each numerical column

df.median(numeric_only=True)

Pregnancies                   3.0000
Glucose                     117.0000
BloodPressure                72.0000
SkinThickness                23.0000
Insulin                      30.5000
BMI                          32.0000
DiabetesPedigreeFunction      0.3725
Age                          29.0000
Outcome                       0.0000
dtype: float64

In [116]:
# 18. Find the minimum value of each column

print(df["Pregnancies"].min())
print(df["Glucose"].min())
print(df["BloodPressure"].min())
print(df["SkinThickness"].min())
print(df["Insulin"].min())
print(df["BMI"].min())
print(df["DiabetesPedigreeFunction"].min())
print(df["Age"].min())

0
0
0
0
0
0.0
0.078
21

In [117]:
# 19. Find the maximum value of each column

print(df["Pregnancies"].max())
print(df["Glucose"].max())
print(df["BloodPressure"].max())
print(df["SkinThickness"].max())
print(df["Insulin"].max())
print(df["BMI"].max())
print(df["DiabetesPedigreeFunction"].max())
print(df["Age"].max())

17
199
122
99
846
67.1
2.42
81

In [118]:
# 20. Find the average glucose level of the patient

df["Glucose"].mean()

120.89453125

In [119]:
# 21. Find the average BMI of the patients

df["BMI"].mean()

31.992578124999977

In [120]:
# 22. Find the average age of the patient

df["Age"].mean()

33.240885416666664

In [121]:
# 23. Find the maximum glocose level

a = df["Glucose"].max()
print("Maximum glocose level: ", a)

Maximum glocose level:  199

In [122]:
# 24. Find the minimum glocose level

a = df["Glucose"].min()
print("Minimum glocose level: ", a)

Minimum glocose level:  0

In [123]:
# 25. Find the average glucose level for diabetics patients only

a = df.loc[df["Outcome"] == 1]["Glucose"].mean()
print("Average glucose level for diabetics patients only: ", a)

Average glucose level for diabetics patients only:  141.25746268656715

In [124]:
# 26. Find the average glucose level for non-diabetics patients only

a = df.loc[df["Outcome"] == 0, "Glucose"].mean()
print("Average glucose level for non-diabetics patients only: ", a)

Average glucose level for non-diabetics patients only:  109.98

In [125]:
# 27. Count the number of diabetics and non-diabetics patient

a = df.loc[df["Outcome"] == 1 ].value_counts().sum()
print("Count the number of diabetics patient: ", a)

b = df.loc[df["Outcome"] == 0 ].value_counts().sum()
print("\nCount the number of non-diabetics patient: ", b)

# outcome_counts = df["Outcome"].value_counts()
# print("Non-diabetic patients: ", outcome_counts.get(0))
# print("Diabetic patients: ", outcome_counts.get(1))

Count the number of diabetics patient:  268

Count the number of non-diabetics patient:  500

In [126]:
# 28. Calculate the percentage of diabetics and non-diabetics patient

total_patient = df.value_counts().sum()
a = df.loc[df["Outcome"] == 1 ].value_counts().sum() 
b = df.loc[df["Outcome"] == 0 ].value_counts().sum()

x = a / total_patient * 100
print("Percentage of diabetics patient: ", x, "%")

y = b / total_patient * 100
print("\nPercentage of non-diabetics patient: ", y, "%")

# outcome_percentage = df["Outcome"].value_counts(normalize=True) * 100

# print("Diabetics: ", outcome_percentage.get(0), "%")

# print("Non-diabetics: ", outcome_percentage.get(1), "%")

Percentage of diabetics patient:  34.89583333333333 %

Percentage of non-diabetics patient:  65.10416666666666 %

In [127]:
# 29. Check whether the dataset contains null values

df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [128]:
# 30. Calculate the total number of null values in the dataset

df.isnull().sum().sum()

0

In [129]:
# 31. Display only the columns that contain null values

df.columns[df.isnull().any()]

Index([], dtype='object')

In [130]:
# 32. Find the percentage of missing values in each column

missing_percentage = df.isnull().mean() * 100
print(missing_percentage)

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

In [131]:
# 33. Check whether any null value exists anywhere in the dataset

df.isnull().values.any()

False

In [132]:
# 34. Count the number of zero values in each columns

zero_count = (df == 0).sum()
print(zero_count)

# df.eq(0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [133]:
# 35. Find the number of zero glucose values

(df["Glucose"] == 0).sum()

5

In [134]:
# 36. Identify the columns where zero may represent missing or invalid data

zero_columns = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
print(zero_columns)

['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

In [151]:
#37. Replace invalid zero values with NaN

import numpy as np

df[zero_columns] = df[zero_columns].replace(0, np.nan)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [144]:
# 38. Check the missing values after replacing zeros with NaN

print(df.isnull().sum())

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [143]:
# 39. Calculate the total number of missing values after replacing zeros

print(df.isnull().sum().sum())

652

In [138]:
# 40. Calculate the percentage of missing values after replacing zeros

print(df.isnull().mean() * 100)

Pregnancies                  0.000000
Glucose                      0.651042
BloodPressure                4.557292
SkinThickness               29.557292
Insulin                     48.697917
BMI                          1.432292
DiabetesPedigreeFunction     0.000000
Age                          0.000000
Outcome                      0.000000
dtype: float64

In [139]:
# 41. Remove all rows containing missing values.

df_clean = df.dropna()

In [141]:
# 42. Display the shape of the original dataset.

print(df.shape)

(768, 9)

In [82]:
# 43. Display the shape of the dataset after removing missing values.

print(df_clean.shape)

(392, 9)

In [83]:
# 44. Check whether any missing values remain after removing rows.

print(df_clean.isnull().values.any())

False

In [85]:
# 45. Create a copy of the dataset before filling missing values.

df_copy = df.copy()

In [86]:
# 46. Fill missing values using the mean.

df_copy = df_copy.fillna(df_copy.mean(numeric_only=True))

In [87]:
# 47. Check the information of the cleaned dataset.

df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [88]:
# 48. Check whether the cleaned dataset contains any missing values.

print(df_copy.isnull().values.any())

False

In [89]:
# 49. Display the statistical summary of the cleaned dataset.

print(df_copy.describe())

       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000
mean      3.845052  121.686763      72.405184      29.153420  155.548223
std       3.369578   30.435949      12.096346       8.790942   85.021108
min       0.000000   44.000000      24.000000       7.000000   14.000000
25%       1.000000   99.750000      64.000000      25.000000  121.500000
50%       3.000000  117.000000      72.202592      29.153420  155.548223
75%       6.000000  140.250000      80.000000      32.000000  155.548223
max      17.000000  199.000000     122.000000      99.000000  846.000000

              BMI  DiabetesPedigreeFunction         Age     Outcome
count  768.000000                768.000000  768.000000  768.000000
mean    32.457464                  0.471876   33.240885    0.348958
std      6.875151                  0.331329   11.760232    0.476951
min     18.200000                  0.078000   21.000000    0.000000
25%     27.500000                  0.243750   24.000000    0.000000
50%     32.400000                  0.372500   29.000000    0.000000
75%     36.600000                  0.626250   41.000000    1.000000
max     67.100000                  2.420000   81.000000    1.000000

In [90]:
# 50.Perform the complete data-cleaning process from loading the dataset to filling missing values using the median.

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("diabetes.csv")

# Columns where 0 is invalid
zero_columns = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

# Replace 0 with NaN
df[zero_columns] = df[zero_columns].replace(0, np.nan)

# Fill missing values using median
df[zero_columns] = df[zero_columns].fillna(df[zero_columns].median())

# Check missing values
print(df.isnull().sum())

# Check information
df.info()

# Display statistical summary
print(df.describe())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB
       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000
mean      3.845052  121.656250      72.386719      29.108073  140.671875
std       3.369578   30.438286      12.096642       8.791221   86.383060
min       0.000000   44.000000      24.000000       7.000000   14.000000
25%       1.000000   99.750000      64.000000      25.000000  121.500000
50%       3.000000  117.000000      72.000000      29.000000  125.000000
75%       6.000000  140.250000      80.000000      32.000000  127.250000
max      17.000000  199.000000     122.000000      99.000000  846.000000

              BMI  DiabetesPedigreeFunction         Age     Outcome
count  768.000000                768.000000  768.000000  768.000000
mean    32.455208                  0.471876   33.240885    0.348958
std      6.875177                  0.331329   11.760232    0.476951
min     18.200000                  0.078000   21.000000    0.000000
25%     27.500000                  0.243750   24.000000    0.000000
50%     32.300000                  0.372500   29.000000    0.000000
75%     36.600000                  0.626250   41.000000    1.000000
max     67.100000                  2.420000   81.000000    1.000000